### PR TITLE
Fix plural forms

### PR DESCRIPTION
**Pull request by metsma**
Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Review by mrts — APPROVED** [review]

**Comment by mrts** [comment]
@mkmayer, can you please review this as well? Our testers found out that without this change the English translation was shown:
image

I.e. the second plural form (`numerusform`) was also required, but is it correct?

**Comment by mkmayer** [comment]
> @mkmayer, can you please review this as well? Our testers found out that without this change the English translation was shown: image
> 
> I.e. the second plural form (`numerusform`) was also required, but is it correct?

Hello, transaltions in cs.ts and sk.ts files are ok, but in my branch, which I merged, I have always maximum of two <numerusform> tags for one translation numerus message. In your main branch cs.ts and sk.ts files, there are three <numerusform> tags for each numerus message tag. The third is extra one, and it shouldn't be there. In both cs and sk files. I think, the problem is, that translation method can't fetch these 3 tags.

**Comment by mkmayer** [comment]
Hello Raul,
see please my commit https://github.com/web-eid/web-eid-app/commit/b33b25289e5f9ed947eebf53aed37fc4a2c4714f. There are the fixed translations. I'm sorry for that numerous tags.

**Comment by metsma** [comment]
> Hello Raul,
> see please my commit [b33b252](https://github.com/web-eid/web-eid-app/commit/b33b25289e5f9ed947eebf53aed37fc4a2c4714f). There are the fixed translations. I'm sorry for that numerous tags. Is it ok to tell it to you this way, or I should do a pull request?

Can you create separate PR for this?

**Pull request merged**
